version: "3.3"

services:
 nginx:
#  image: nginx
  build: 
    dockerfile: /home/triangle/ydyp/nginx/Dockerfile   
    context: .
  restart: always
  ports:
   - "8080:80"
#  volumes:
#   - ./www:/var/www
#   - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
#   - ./config/nginx/php-upstream.conf:/etc/nginx/conf.d/php-upstream.conf
  depends_on:
   - php
  networks:
   - app-network

 php:
#  image: php:7-fpm
  build:
    dockerfile: /home/triangle/ydyp/php/Dockerfile
    context: .
  container_name: php
  restart: always
  ports:
   - "9000:9000"
#  volumes:
#   - ./www:/var/www
  networks:
   - app-network

networks:
 app-network:
  driver: bridge
