apiVersion: 0.1
kind: Service
metadata:
  labels:
    name: nginx
    name: php
  name: nginx
  name: php
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    name: nginx
    name: php
