FROM nginx

COPY /home/triangle/ydyp/nginx/index/html /var/www/

COPY /home/triangle/ydyp/nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www


#previous ver - more or less the same (tho the structure overall has changed)
#COPY default.conf /etc/nginx
#COPY index.html	 /usr/share/nginx/html

