FROM test

COPY /home/triangle/ydyp/config/nginx/default.conf /etc/nginx/

COPY /home/tr/www/html/hello.dev	 /usr/share/nginx/html

VOLUME /home/triangle/ydyp/www/html/hello.dev
VOLUME /home/triangle/ydyp/config/nginx
#VOLUME /usr/share/nginx/html
#VOLUME /etc/nginx
